// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (id, user_id, token_hash, expires_at, ip_address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, is_revoked, created_at, last_used_at, ip_address
`

type CreateAccessTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress *string            `json:"ip_address"`
}

// ID генерируется на стороне сервиса (uuid.New()), потому что он же
// используется как jti в JWT-claims — необходимо знать значение до
// подписи токена.
func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IpAddress,
	)
	return i, err
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :execrows
DELETE FROM access_tokens
WHERE expires_at < NOW() - INTERVAL '7 days'
`

// Периодическая чистка таблицы фоновой задачей.
func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAccessTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, user_id, token_hash, expires_at, is_revoked, created_at, last_used_at, ip_address
FROM access_tokens
WHERE token_hash = $1
  AND is_revoked = FALSE
  AND expires_at > NOW()
`

// Используется в auth-middleware для проверки выданного access-токена.
// Возвращает запись только если она активна (не отозвана и не истекла).
func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, tokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IpAddress,
	)
	return i, err
}

const getAccessTokenByID = `-- name: GetAccessTokenByID :one
SELECT id, user_id, token_hash, expires_at, is_revoked, created_at, last_used_at, ip_address
FROM access_tokens
WHERE id = $1
`

func (q *Queries) GetAccessTokenByID(ctx context.Context, id pgtype.UUID) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByID, id)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IpAddress,
	)
	return i, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
UPDATE access_tokens
SET is_revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeAccessToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, id)
	return err
}

const revokeAllAccessTokensForUser = `-- name: RevokeAllAccessTokensForUser :exec
UPDATE access_tokens
SET is_revoked = TRUE
WHERE user_id = $1
  AND is_revoked = FALSE
`

// Используется при logout-all и при детекте повторного использования
// refresh-токена (защита от replay).
func (q *Queries) RevokeAllAccessTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAccessTokensForUser, userID)
	return err
}

const touchAccessToken = `-- name: TouchAccessToken :exec
UPDATE access_tokens
SET last_used_at = NOW()
WHERE id = $1
`

// Обновляет last_used_at при успешной проверке токена в middleware.
func (q *Queries) TouchAccessToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAccessToken, id)
	return err
}
