// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO audit_log (actor_id, action, target_type, target_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_id, action, target_type, target_id, details, ip_address, created_at
`

type CreateAuditEntryParams struct {
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType string      `json:"target_type"`
	TargetID   *string     `json:"target_id"`
	Details    []byte      `json:"details"`
	IpAddress  *string     `json:"ip_address"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditEntry,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditByActor = `-- name: ListAuditByActor :many
SELECT id, actor_id, action, target_type, target_id, details, ip_address, created_at
FROM audit_log
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditByActorParams struct {
	ActorID pgtype.UUID `json:"actor_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByActor, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTarget = `-- name: ListAuditByTarget :many
SELECT id, actor_id, action, target_type, target_id, details, ip_address, created_at
FROM audit_log
WHERE target_type = $1
  AND target_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditByTargetParams struct {
	TargetType string  `json:"target_type"`
	TargetID   *string `json:"target_id"`
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
}

func (q *Queries) ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTarget,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAudit = `-- name: ListRecentAudit :many
SELECT id, actor_id, action, target_type, target_id, details, ip_address, created_at
FROM audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentAuditParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentAudit(ctx context.Context, arg ListRecentAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
