// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_logs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChangeLog = `-- name: CreateChangeLog :one
INSERT INTO change_logs (entity_type, entity_id, action, before, after, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entity_type, entity_id, action, before, after, created_at, created_by
`

type CreateChangeLogParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   string      `json:"entity_id"`
	Action     string      `json:"action"`
	Before     []byte      `json:"before"`
	After      []byte      `json:"after"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, createChangeLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Before,
		arg.After,
		arg.CreatedBy,
	)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Before,
		&i.After,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getChangeLogByID = `-- name: GetChangeLogByID :one
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE id = $1
`

func (q *Queries) GetChangeLogByID(ctx context.Context, id int64) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, getChangeLogByID, id)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Before,
		&i.After,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listChangeLogsByAuthor = `-- name: ListChangeLogsByAuthor :many
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChangeLogsByAuthorParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListChangeLogsByAuthor(ctx context.Context, arg ListChangeLogsByAuthorParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsByAuthor, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeLog
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeLogsByEntityType = `-- name: ListChangeLogsByEntityType :many
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE entity_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChangeLogsByEntityTypeParams struct {
	EntityType string `json:"entity_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListChangeLogsByEntityType(ctx context.Context, arg ListChangeLogsByEntityTypeParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsByEntityType, arg.EntityType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeLog
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeLogsForEntity = `-- name: ListChangeLogsForEntity :many
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE entity_type = $1
  AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListChangeLogsForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

// История изменений конкретной сущности — лента "что менялось у этого
// долга / пересдачи / роли". Используется при выводе story-страницы.
func (q *Queries) ListChangeLogsForEntity(ctx context.Context, arg ListChangeLogsForEntityParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsForEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeLog
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
