// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debts.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDebt = `-- name: CancelDebt :exec
UPDATE debts
SET status     = 'cancelled',
    updated_at = NOW()
WHERE id = $1
  AND status = 'open'
  AND deleted_at IS NULL
`

// Деканат отменяет ошибочно поставленный долг.
func (q *Queries) CancelDebt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelDebt, id)
	return err
}

const countDebts = `-- name: CountDebts :one
SELECT COUNT(*) FROM debts WHERE deleted_at IS NULL
`

func (q *Queries) CountDebts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDebts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenDebtsForStudent = `-- name: CountOpenDebtsForStudent :one
SELECT COUNT(*)
FROM debts
WHERE student_id = $1
  AND status = 'open'
  AND deleted_at IS NULL
`

func (q *Queries) CountOpenDebtsForStudent(ctx context.Context, studentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenDebtsForStudent, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (student_id, discipline_id, issued_by, external_id, source, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
`

type CreateDebtParams struct {
	StudentID    pgtype.UUID `json:"student_id"`
	DisciplineID pgtype.UUID `json:"discipline_id"`
	IssuedBy     pgtype.UUID `json:"issued_by"`
	ExternalID   *string     `json:"external_id"`
	Source       string      `json:"source"`
	Notes        *string     `json:"notes"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.StudentID,
		arg.DisciplineID,
		arg.IssuedBy,
		arg.ExternalID,
		arg.Source,
		arg.Notes,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisciplineID,
		&i.IssuedBy,
		&i.Status,
		&i.FinalGrade,
		&i.GradedAt,
		&i.GradedBy,
		&i.ExternalID,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getDebtByExternalID = `-- name: GetDebtByExternalID :one
SELECT id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
FROM debts
WHERE external_id = $1
  AND deleted_at IS NULL
`

// Используется синхронизатором: повторный pull из внешней системы
// не создаёт дубль, а обновляет существующий долг.
func (q *Queries) GetDebtByExternalID(ctx context.Context, externalID *string) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByExternalID, externalID)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisciplineID,
		&i.IssuedBy,
		&i.Status,
		&i.FinalGrade,
		&i.GradedAt,
		&i.GradedBy,
		&i.ExternalID,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
FROM debts
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDebtByID(ctx context.Context, id pgtype.UUID) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisciplineID,
		&i.IssuedBy,
		&i.Status,
		&i.FinalGrade,
		&i.GradedAt,
		&i.GradedBy,
		&i.ExternalID,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const gradeDebt = `-- name: GradeDebt :one
UPDATE debts
SET status      = 'graded',
    final_grade = $2,
    graded_at   = NOW(),
    graded_by   = $3,
    updated_at  = NOW()
WHERE id = $1
  AND status = 'open'
  AND deleted_at IS NULL
RETURNING id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
`

type GradeDebtParams struct {
	ID         pgtype.UUID `json:"id"`
	FinalGrade *int32      `json:"final_grade"`
	GradedBy   pgtype.UUID `json:"graded_by"`
}

// Перевод долга в graded со всеми требуемыми CHECK-полями.
// Сервис вызывает это в одной транзакции с обновлением
// retake_participants.grade на соответствующей пересдаче.
func (q *Queries) GradeDebt(ctx context.Context, arg GradeDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, gradeDebt, arg.ID, arg.FinalGrade, arg.GradedBy)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisciplineID,
		&i.IssuedBy,
		&i.Status,
		&i.FinalGrade,
		&i.GradedAt,
		&i.GradedBy,
		&i.ExternalID,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listAllDebts = `-- name: ListAllDebts :many
SELECT id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
FROM debts
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllDebtsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Деканат: общий список (debts.view.all) с пагинацией.
func (q *Queries) ListAllDebts(ctx context.Context, arg ListAllDebtsParams) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listAllDebts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.DisciplineID,
			&i.IssuedBy,
			&i.Status,
			&i.FinalGrade,
			&i.GradedAt,
			&i.GradedBy,
			&i.ExternalID,
			&i.Source,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtorsByDiscipline = `-- name: ListDebtorsByDiscipline :many
SELECT
    d.id            AS debt_id,
    d.student_id,
    u.first_name,
    u.last_name,
    u.middle_name,
    u.group_name
FROM debts d
JOIN users u ON u.id = d.student_id
WHERE d.discipline_id = $1
  AND d.status = 'open'
  AND d.deleted_at IS NULL
ORDER BY u.last_name ASC, u.first_name ASC
`

type ListDebtorsByDisciplineRow struct {
	DebtID     pgtype.UUID `json:"debt_id"`
	StudentID  pgtype.UUID `json:"student_id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	MiddleName *string     `json:"middle_name"`
	GroupName  *string     `json:"group_name"`
}

// Преподаватель видит должников по конкретной дисциплине с ФИО+группой —
// нужно для формы заявки на пересдачу (выбрать кого записывать).
// JOIN с users безопасен: возвращаем только тех студентов, у кого есть
// открытый долг по дисциплине, то есть тех, кого actor и так видит
// через GET /api/debts/by-discipline. Без password_hash и т.п.
func (q *Queries) ListDebtorsByDiscipline(ctx context.Context, disciplineID pgtype.UUID) ([]ListDebtorsByDisciplineRow, error) {
	rows, err := q.db.Query(ctx, listDebtorsByDiscipline, disciplineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebtorsByDisciplineRow
	for rows.Next() {
		var i ListDebtorsByDisciplineRow
		if err := rows.Scan(
			&i.DebtID,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsByDiscipline = `-- name: ListDebtsByDiscipline :many
SELECT id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
FROM debts
WHERE discipline_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDebtsByDisciplineParams struct {
	DisciplineID pgtype.UUID `json:"discipline_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

// Преподаватель: должники по конкретной дисциплине. Сервис
// предварительно проверяет teacher_disciplines.IsTeacherOfDiscipline.
func (q *Queries) ListDebtsByDiscipline(ctx context.Context, arg ListDebtsByDisciplineParams) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebtsByDiscipline, arg.DisciplineID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.DisciplineID,
			&i.IssuedBy,
			&i.Status,
			&i.FinalGrade,
			&i.GradedAt,
			&i.GradedBy,
			&i.ExternalID,
			&i.Source,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsByDisciplines = `-- name: ListDebtsByDisciplines :many
SELECT id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
FROM debts
WHERE discipline_id = ANY($1::uuid[])
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListDebtsByDisciplinesParams struct {
	DisciplineIds []pgtype.UUID `json:"discipline_ids"`
	Off           int32         `json:"off"`
	Lim           int32         `json:"lim"`
}

// Преподаватель: должники по всем своим дисциплинам разом.
// Передаётся массив id, который сервис собирает из ListDisciplines-
// ForTeacher. Это эффективнее, чем N+1 запрос.
func (q *Queries) ListDebtsByDisciplines(ctx context.Context, arg ListDebtsByDisciplinesParams) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebtsByDisciplines, arg.DisciplineIds, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.DisciplineID,
			&i.IssuedBy,
			&i.Status,
			&i.FinalGrade,
			&i.GradedAt,
			&i.GradedBy,
			&i.ExternalID,
			&i.Source,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsForStudent = `-- name: ListDebtsForStudent :many
SELECT id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
FROM debts
WHERE student_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// Студент видит свои долги (permission debts.view.own).
func (q *Queries) ListDebtsForStudent(ctx context.Context, studentID pgtype.UUID) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebtsForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.DisciplineID,
			&i.IssuedBy,
			&i.Status,
			&i.FinalGrade,
			&i.GradedAt,
			&i.GradedBy,
			&i.ExternalID,
			&i.Source,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisciplineIDsByIssuer = `-- name: ListDisciplineIDsByIssuer :many
SELECT DISTINCT discipline_id
FROM debts
WHERE issued_by = $1
  AND deleted_at IS NULL
`

// "Свои предметы" преподавателя = дисциплины, по которым ОН ставил долги
// (debts.issued_by). Эмулятор не отдаёт явную связь teacher↔discipline,
// но в каждом долге есть issued_by (= TeacherID из эмулятора, "препод,
// поставивший долг" по ТЗ). Поэтому дисциплины препода выводим отсюда.
// Используется в debt.Service.ListForTeacher как замена пустой
// teacher_disciplines.
func (q *Queries) ListDisciplineIDsByIssuer(ctx context.Context, issuedBy pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDisciplineIDsByIssuer, issuedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var discipline_id pgtype.UUID
		if err := rows.Scan(&discipline_id); err != nil {
			return nil, err
		}
		items = append(items, discipline_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenDebt = `-- name: ReopenDebt :one
UPDATE debts
SET status      = 'open',
    final_grade = NULL,
    graded_at   = NULL,
    graded_by   = NULL,
    updated_at  = NOW()
WHERE id = $1
  AND status = 'graded'
  AND deleted_at IS NULL
RETURNING id, student_id, discipline_id, issued_by, status, final_grade, graded_at, graded_by, external_id, source, notes, created_at, updated_at, deleted_at, deleted_by
`

// Откат закрытия долга при «Открыть ведомость» (декан): graded → open.
// CHECK debts_grade_consistency требует, чтобы у open-долга
// final_grade/graded_at/graded_by были NULL — обнуляем их.
// ВНИМАНИЕ: idx_debts_unique_open запрещает 2 open-долга по одной паре
// (student, discipline). Если sync создал новый open-долг после закрытия
// ведомости — этот UPDATE упадёт с 23505, сервис ловит и пропускает
// (best-effort per debt), ведомость всё равно открывается.
func (q *Queries) ReopenDebt(ctx context.Context, id pgtype.UUID) (Debt, error) {
	row := q.db.QueryRow(ctx, reopenDebt, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisciplineID,
		&i.IssuedBy,
		&i.Status,
		&i.FinalGrade,
		&i.GradedAt,
		&i.GradedBy,
		&i.ExternalID,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const softDeleteDebt = `-- name: SoftDeleteDebt :exec
UPDATE debts
SET deleted_at = NOW(),
    deleted_by = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type SoftDeleteDebtParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteDebt(ctx context.Context, arg SoftDeleteDebtParams) error {
	_, err := q.db.Exec(ctx, softDeleteDebt, arg.ID, arg.DeletedBy)
	return err
}

const summaryDebtsByDiscipline = `-- name: SummaryDebtsByDiscipline :many
SELECT
    d.discipline_id,
    COUNT(*) FILTER (WHERE d.status = 'open')   AS open_count,
    COUNT(*) FILTER (WHERE d.status = 'graded') AS graded_count
FROM debts d
WHERE d.deleted_at IS NULL
GROUP BY d.discipline_id
ORDER BY open_count DESC
`

type SummaryDebtsByDisciplineRow struct {
	DisciplineID pgtype.UUID `json:"discipline_id"`
	OpenCount    int64       `json:"open_count"`
	GradedCount  int64       `json:"graded_count"`
}

// Сводная для деканата: сколько открытых долгов и сколько
// закрытых оценкой по каждой дисциплине.
func (q *Queries) SummaryDebtsByDiscipline(ctx context.Context) ([]SummaryDebtsByDisciplineRow, error) {
	rows, err := q.db.Query(ctx, summaryDebtsByDiscipline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryDebtsByDisciplineRow
	for rows.Next() {
		var i SummaryDebtsByDisciplineRow
		if err := rows.Scan(&i.DisciplineID, &i.OpenCount, &i.GradedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
