// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disciplines.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDisciplines = `-- name: CountDisciplines :one
SELECT COUNT(*) FROM disciplines WHERE deleted_at IS NULL
`

func (q *Queries) CountDisciplines(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDisciplines)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDiscipline = `-- name: CreateDiscipline :one
INSERT INTO disciplines (name, code, description, external_id, source, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, code, description, external_id, source, created_at, created_by, updated_at, deleted_at, deleted_by
`

type CreateDisciplineParams struct {
	Name        string      `json:"name"`
	Code        string      `json:"code"`
	Description *string     `json:"description"`
	ExternalID  *string     `json:"external_id"`
	Source      string      `json:"source"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDiscipline(ctx context.Context, arg CreateDisciplineParams) (Discipline, error) {
	row := q.db.QueryRow(ctx, createDiscipline,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.ExternalID,
		arg.Source,
		arg.CreatedBy,
	)
	var i Discipline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getDisciplineByCode = `-- name: GetDisciplineByCode :one
SELECT id, name, code, description, external_id, source, created_at, created_by, updated_at, deleted_at, deleted_by
FROM disciplines
WHERE LOWER(code) = LOWER($1)
  AND deleted_at IS NULL
`

func (q *Queries) GetDisciplineByCode(ctx context.Context, lower string) (Discipline, error) {
	row := q.db.QueryRow(ctx, getDisciplineByCode, lower)
	var i Discipline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getDisciplineByExternalID = `-- name: GetDisciplineByExternalID :one
SELECT id, name, code, description, external_id, source, created_at, created_by, updated_at, deleted_at, deleted_by
FROM disciplines
WHERE external_id = $1
  AND deleted_at IS NULL
`

// Используется при синхронизации: если запись уже есть, делаем UPDATE,
// иначе CREATE.
func (q *Queries) GetDisciplineByExternalID(ctx context.Context, externalID *string) (Discipline, error) {
	row := q.db.QueryRow(ctx, getDisciplineByExternalID, externalID)
	var i Discipline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getDisciplineByID = `-- name: GetDisciplineByID :one
SELECT id, name, code, description, external_id, source, created_at, created_by, updated_at, deleted_at, deleted_by
FROM disciplines
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDisciplineByID(ctx context.Context, id pgtype.UUID) (Discipline, error) {
	row := q.db.QueryRow(ctx, getDisciplineByID, id)
	var i Discipline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listDisciplines = `-- name: ListDisciplines :many
SELECT id, name, code, description, external_id, source, created_at, created_by, updated_at, deleted_at, deleted_by
FROM disciplines
WHERE deleted_at IS NULL
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListDisciplinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDisciplines(ctx context.Context, arg ListDisciplinesParams) ([]Discipline, error) {
	rows, err := q.db.Query(ctx, listDisciplines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Discipline
	for rows.Next() {
		var i Discipline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.ExternalID,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisciplinesByIDs = `-- name: ListDisciplinesByIDs :many
SELECT id, name, code, description, external_id, source, created_at, created_by, updated_at, deleted_at, deleted_by
FROM disciplines
WHERE id = ANY($1::uuid[])
  AND deleted_at IS NULL
`

// Батч-выборка дисциплин по списку ID. Используется в report.Service
// вместо N одиночных GetDisciplineByID.
func (q *Queries) ListDisciplinesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Discipline, error) {
	rows, err := q.db.Query(ctx, listDisciplinesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Discipline
	for rows.Next() {
		var i Discipline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.ExternalID,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDiscipline = `-- name: RestoreDiscipline :exec
UPDATE disciplines
SET deleted_at = NULL,
    deleted_by = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreDiscipline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreDiscipline, id)
	return err
}

const softDeleteDiscipline = `-- name: SoftDeleteDiscipline :exec
UPDATE disciplines
SET deleted_at = NOW(),
    deleted_by = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SoftDeleteDisciplineParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteDiscipline(ctx context.Context, arg SoftDeleteDisciplineParams) error {
	_, err := q.db.Exec(ctx, softDeleteDiscipline, arg.ID, arg.DeletedBy)
	return err
}

const updateDiscipline = `-- name: UpdateDiscipline :one
UPDATE disciplines
SET name        = COALESCE($1,        name),
    code        = COALESCE($2,        code),
    description = COALESCE($3, description),
    updated_at  = NOW()
WHERE id = $4
  AND deleted_at IS NULL
RETURNING id, name, code, description, external_id, source, created_at, created_by, updated_at, deleted_at, deleted_by
`

type UpdateDisciplineParams struct {
	Name        *string     `json:"name"`
	Code        *string     `json:"code"`
	Description *string     `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDiscipline(ctx context.Context, arg UpdateDisciplineParams) (Discipline, error) {
	row := q.db.QueryRow(ctx, updateDiscipline,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.ID,
	)
	var i Discipline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.ExternalID,
		&i.Source,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
