// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	IsRevoked  bool               `json:"is_revoked"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	IpAddress  *string            `json:"ip_address"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   *string            `json:"target_id"`
	Details    []byte             `json:"details"`
	IpAddress  *string            `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChangeLog struct {
	ID         int64              `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Action     string             `json:"action"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
}

type PermissionRole struct {
	ID           pgtype.UUID        `json:"id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
}

type RefreshToken struct {
	ID            pgtype.UUID        `json:"id"`
	AccessTokenID pgtype.UUID        `json:"access_token_id"`
	TokenHash     string             `json:"token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	IsUsed        bool               `json:"is_used"`
	IsRevoked     bool               `json:"is_revoked"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	Level       int32              `json:"level"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
}

type RoleUser struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	MiddleName   *string            `json:"middle_name"`
	Birthday     pgtype.Date        `json:"birthday"`
	GroupName    *string            `json:"group_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
