// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (name, slug, description, is_system, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, description, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
`

type CreatePermissionParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description *string     `json:"description"`
	IsSystem    bool        `json:"is_system"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsSystem,
		arg.CreatedBy,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, name, slug, description, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
FROM permissions
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPermissionByID(ctx context.Context, id pgtype.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPermissionBySlug = `-- name: GetPermissionBySlug :one
SELECT id, name, slug, description, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
FROM permissions
WHERE LOWER(slug) = LOWER($1)
  AND deleted_at IS NULL
`

func (q *Queries) GetPermissionBySlug(ctx context.Context, lower string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionBySlug, lower)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name, slug, description, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
FROM permissions
WHERE deleted_at IS NULL
ORDER BY slug ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePermission = `-- name: RestorePermission :exec
UPDATE permissions
SET deleted_at = NULL,
    deleted_by = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestorePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePermission, id)
	return err
}

const softDeletePermission = `-- name: SoftDeletePermission :exec
UPDATE permissions
SET deleted_at = NOW(),
    deleted_by = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SoftDeletePermissionParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeletePermission(ctx context.Context, arg SoftDeletePermissionParams) error {
	_, err := q.db.Exec(ctx, softDeletePermission, arg.ID, arg.DeletedBy)
	return err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET name        = COALESCE($1,        name),
    description = COALESCE($2, description),
    updated_at  = NOW()
WHERE id = $3
  AND deleted_at IS NULL
RETURNING id, name, slug, description, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
`

type UpdatePermissionParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission, arg.Name, arg.Description, arg.ID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
