// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission_role.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPermissionToRole = `-- name: AttachPermissionToRole :one
INSERT INTO permission_role (role_id, permission_id, created_by)
VALUES ($1, $2, $3)
RETURNING id, role_id, permission_id, created_at, created_by, deleted_at, deleted_by
`

type AttachPermissionToRoleParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) AttachPermissionToRole(ctx context.Context, arg AttachPermissionToRoleParams) (PermissionRole, error) {
	row := q.db.QueryRow(ctx, attachPermissionToRole, arg.RoleID, arg.PermissionID, arg.CreatedBy)
	var i PermissionRole
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const detachPermissionFromRole = `-- name: DetachPermissionFromRole :exec
UPDATE permission_role
SET deleted_at = NOW(),
    deleted_by = $3
WHERE role_id = $1
  AND permission_id = $2
  AND deleted_at IS NULL
`

type DetachPermissionFromRoleParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	DeletedBy    pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DetachPermissionFromRole(ctx context.Context, arg DetachPermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, detachPermissionFromRole, arg.RoleID, arg.PermissionID, arg.DeletedBy)
	return err
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT p.id, p.name, p.slug, p.description, p.is_system, p.created_at, p.created_by, p.updated_at, p.deleted_at, p.deleted_by
FROM permissions p
JOIN permission_role pr ON pr.permission_id = p.id
WHERE pr.role_id = $1
  AND pr.deleted_at IS NULL
  AND p.deleted_at IS NULL
ORDER BY p.slug ASC
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
