// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachPermissionToRole(ctx context.Context, arg AttachPermissionToRoleParams) (PermissionRole, error)
	// Идемпотентно: при повторной выдаче той же роли SoftDelete ничего не
	// меняет, INSERT даст конфликт по уникальному индексу. Идемпотентность
	// обеспечивается на уровне сервиса (сначала проверка существования).
	AttachRoleToUser(ctx context.Context, arg AttachRoleToUserParams) (RoleUser, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error)
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditLog, error)
	CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Периодическая чистка таблицы фоновой задачей.
	DeleteExpiredAccessTokens(ctx context.Context) (int64, error)
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DetachPermissionFromRole(ctx context.Context, arg DetachPermissionFromRoleParams) error
	DetachRoleFromUser(ctx context.Context, arg DetachRoleFromUserParams) error
	// Используется в auth-middleware для проверки выданного access-токена.
	// Возвращает запись только если она активна (не отозвана и не истекла).
	GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error)
	GetAccessTokenByID(ctx context.Context, id pgtype.UUID) (AccessToken, error)
	GetChangeLogByID(ctx context.Context, id int64) (ChangeLog, error)
	GetPermissionByID(ctx context.Context, id pgtype.UUID) (Permission, error)
	GetPermissionBySlug(ctx context.Context, lower string) (Permission, error)
	// Возвращает запись по хешу. Сервис auth дополнительно проверяет is_used
	// и is_revoked — если is_used=TRUE при попытке refresh, это replay
	// и сервис должен отозвать все токены пользователя.
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error)
	GetRoleBySlug(ctx context.Context, lower string) (Role, error)
	// Поиск пользователя по email для логина. Сравнение регистронезависимое
	// (соответствует UNIQUE-индексу idx_users_email_lower).
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Проверка наличия конкретной роли у пользователя.
	HasRole(ctx context.Context, arg HasRoleParams) (bool, error)
	ListAuditByActor(ctx context.Context, arg ListAuditByActorParams) ([]AuditLog, error)
	ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error)
	ListChangeLogsByAuthor(ctx context.Context, arg ListChangeLogsByAuthorParams) ([]ChangeLog, error)
	ListChangeLogsByEntityType(ctx context.Context, arg ListChangeLogsByEntityTypeParams) ([]ChangeLog, error)
	// История изменений конкретной сущности — лента "что менялось у этого
	// долга / пересдачи / роли". Используется при выводе story-страницы.
	ListChangeLogsForEntity(ctx context.Context, arg ListChangeLogsForEntityParams) ([]ChangeLog, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error)
	// Возвращает все активные slug'и разрешений, доступных пользователю
	// через его роли. Дубли убираются DISTINCT, потому что один permission
	// может быть прикреплён к нескольким ролям пользователя.
	ListPermissionsForUser(ctx context.Context, userID pgtype.UUID) ([]string, error)
	ListRecentAudit(ctx context.Context, arg ListRecentAuditParams) ([]AuditLog, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRolesForUser(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	// Для админ-интерфейса просмотра истории.
	ListRolesIncludingDeleted(ctx context.Context) ([]Role, error)
	// Пагинация: LIMIT $1, OFFSET $2. Сортировка по дате создания убывающая
	// (новые сверху), стабильный tie-break через id.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersInRole(ctx context.Context, roleID pgtype.UUID) ([]User, error)
	MarkRefreshTokenUsed(ctx context.Context, id pgtype.UUID) error
	RestorePermission(ctx context.Context, id pgtype.UUID) error
	RestoreRole(ctx context.Context, id pgtype.UUID) error
	RevokeAccessToken(ctx context.Context, id pgtype.UUID) error
	// Используется при logout-all и при детекте повторного использования
	// refresh-токена (защита от replay).
	RevokeAllAccessTokensForUser(ctx context.Context, userID pgtype.UUID) error
	// Отзыв всех refresh-токенов, связанных с конкретным access-токеном.
	RevokeAllRefreshTokensForAccessToken(ctx context.Context, accessTokenID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SoftDeletePermission(ctx context.Context, arg SoftDeletePermissionParams) error
	// Системные роли (is_system=TRUE) защищаются от удаления на уровне
	// сервиса — здесь жёсткой проверки нет, чтобы запрос оставался
	// переиспользуемым.
	SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error
	// Обновляет last_used_at при успешной проверке токена в middleware.
	TouchAccessToken(ctx context.Context, id pgtype.UUID) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Точечное обновление профиля. NULL-значения в параметрах оставляют поле
	// без изменений (COALESCE), что упрощает PATCH-семантику на handler-слое.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Точечная проверка на конкретный permission по slug. Используется в
	// RBAC-middleware на каждом защищённом запросе.
	UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
