// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (access_token_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, access_token_id, token_hash, expires_at, is_used, is_revoked, created_at
`

type CreateRefreshTokenParams struct {
	AccessTokenID pgtype.UUID        `json:"access_token_id"`
	TokenHash     string             `json:"token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.AccessTokenID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccessTokenID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, access_token_id, token_hash, expires_at, is_used, is_revoked, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

// Возвращает запись по хешу. Сервис auth дополнительно проверяет is_used
// и is_revoked — если is_used=TRUE при попытке refresh, это replay
// и сервис должен отозвать все токены пользователя.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccessTokenID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, access_token_id, token_hash, expires_at, is_used, is_revoked, created_at
FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

// То же, что GetRefreshTokenByHash, но с блокировкой строки FOR UPDATE.
// Используется внутри RunInTx в token.Rotate, чтобы две параллельные
// попытки обмена одного refresh не прошли проверку is_used=FALSE
// одновременно — второй вызов будет ждать коммита первого.
func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccessTokenID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens
SET is_used = TRUE
WHERE id = $1
`

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}

const revokeAllRefreshTokensForAccessToken = `-- name: RevokeAllRefreshTokensForAccessToken :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE access_token_id = $1
  AND is_revoked = FALSE
`

// Отзыв всех refresh-токенов, связанных с конкретным access-токеном.
func (q *Queries) RevokeAllRefreshTokensForAccessToken(ctx context.Context, accessTokenID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForAccessToken, accessTokenID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET is_revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
