// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retakes.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRetake = `-- name: CancelRetake :exec
UPDATE retakes
SET status     = 'cancelled',
    updated_at = NOW()
WHERE id = $1
  AND status IN ('scheduled', 'in_progress')
  AND deleted_at IS NULL
`

func (q *Queries) CancelRetake(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelRetake, id)
	return err
}

const createRetake = `-- name: CreateRetake :one
INSERT INTO retakes (discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, created_by, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, status, completed_at, created_by, notes, created_at, updated_at, deleted_at, deleted_by
`

type CreateRetakeParams struct {
	DisciplineID    pgtype.UUID        `json:"discipline_id"`
	Kind            string             `json:"kind"`
	MinTeachers     int32              `json:"min_teachers"`
	Building        string             `json:"building"`
	Room            string             `json:"room"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Notes           *string            `json:"notes"`
}

func (q *Queries) CreateRetake(ctx context.Context, arg CreateRetakeParams) (Retake, error) {
	row := q.db.QueryRow(ctx, createRetake,
		arg.DisciplineID,
		arg.Kind,
		arg.MinTeachers,
		arg.Building,
		arg.Room,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.CreatedBy,
		arg.Notes,
	)
	var i Retake
	err := row.Scan(
		&i.ID,
		&i.DisciplineID,
		&i.Kind,
		&i.MinTeachers,
		&i.Building,
		&i.Room,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getRetakeByID = `-- name: GetRetakeByID :one
SELECT id, discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, status, completed_at, created_by, notes, created_at, updated_at, deleted_at, deleted_by
FROM retakes
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetRetakeByID(ctx context.Context, id pgtype.UUID) (Retake, error) {
	row := q.db.QueryRow(ctx, getRetakeByID, id)
	var i Retake
	err := row.Scan(
		&i.ID,
		&i.DisciplineID,
		&i.Kind,
		&i.MinTeachers,
		&i.Building,
		&i.Room,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listRetakes = `-- name: ListRetakes :many
SELECT id, discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, status, completed_at, created_by, notes, created_at, updated_at, deleted_at, deleted_by
FROM retakes
WHERE deleted_at IS NULL
  AND ($1::varchar IS NULL OR status = $1)
ORDER BY scheduled_at DESC
LIMIT $3 OFFSET $2
`

type ListRetakesParams struct {
	Status *string `json:"status"`
	Off    int32   `json:"off"`
	Lim    int32   `json:"lim"`
}

// Деканат: общий список пересдач, с фильтром по статусу при необходимости.
// sqlc.narg('status') NULL означает "все статусы".
func (q *Queries) ListRetakes(ctx context.Context, arg ListRetakesParams) ([]Retake, error) {
	rows, err := q.db.Query(ctx, listRetakes, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Retake
	for rows.Next() {
		var i Retake
		if err := rows.Scan(
			&i.ID,
			&i.DisciplineID,
			&i.Kind,
			&i.MinTeachers,
			&i.Building,
			&i.Room,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetakesForUser = `-- name: ListRetakesForUser :many
SELECT DISTINCT r.id, r.discipline_id, r.kind, r.min_teachers, r.building, r.room, r.scheduled_at, r.duration_minutes, r.status, r.completed_at, r.created_by, r.notes, r.created_at, r.updated_at, r.deleted_at, r.deleted_by
FROM retakes r
JOIN retake_participants rp ON rp.retake_id = r.id
WHERE rp.user_id = $1
  AND r.deleted_at IS NULL
ORDER BY r.scheduled_at DESC
`

// Все пересдачи, в которых пользователь — участник (любой kind).
// Используется в личном кабинете студента и преподавателя
// (permission retakes.view.own).
func (q *Queries) ListRetakesForUser(ctx context.Context, userID pgtype.UUID) ([]Retake, error) {
	rows, err := q.db.Query(ctx, listRetakesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Retake
	for rows.Next() {
		var i Retake
		if err := rows.Scan(
			&i.ID,
			&i.DisciplineID,
			&i.Kind,
			&i.MinTeachers,
			&i.Building,
			&i.Room,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetakesInPeriod = `-- name: ListRetakesInPeriod :many
SELECT id, discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, status, completed_at, created_by, notes, created_at, updated_at, deleted_at, deleted_by
FROM retakes
WHERE deleted_at IS NULL
  AND status = 'completed'
  AND completed_at >= $1
  AND completed_at <  $2
ORDER BY completed_at ASC
`

type ListRetakesInPeriodParams struct {
	From pgtype.Timestamptz `json:"from"`
	To   pgtype.Timestamptz `json:"to"`
}

// Для сводного отчёта деканата за период: только проведённые.
func (q *Queries) ListRetakesInPeriod(ctx context.Context, arg ListRetakesInPeriodParams) ([]Retake, error) {
	rows, err := q.db.Query(ctx, listRetakesInPeriod, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Retake
	for rows.Next() {
		var i Retake
		if err := rows.Scan(
			&i.ID,
			&i.DisciplineID,
			&i.Kind,
			&i.MinTeachers,
			&i.Building,
			&i.Room,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetakesToFinish = `-- name: ListRetakesToFinish :many
SELECT id, discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, status, completed_at, created_by, notes, created_at, updated_at, deleted_at, deleted_by
FROM retakes
WHERE status IN ('scheduled', 'in_progress')
  AND (scheduled_at + (duration_minutes || ' minutes')::interval) <= NOW()
  AND deleted_at IS NULL
ORDER BY scheduled_at ASC
`

// Шедулер: пересдачи, которые пора завершать (scheduled_at + duration < NOW()).
func (q *Queries) ListRetakesToFinish(ctx context.Context) ([]Retake, error) {
	rows, err := q.db.Query(ctx, listRetakesToFinish)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Retake
	for rows.Next() {
		var i Retake
		if err := rows.Scan(
			&i.ID,
			&i.DisciplineID,
			&i.Kind,
			&i.MinTeachers,
			&i.Building,
			&i.Room,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetakesToStart = `-- name: ListRetakesToStart :many
SELECT id, discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, status, completed_at, created_by, notes, created_at, updated_at, deleted_at, deleted_by
FROM retakes
WHERE status = 'scheduled'
  AND scheduled_at <= NOW()
  AND deleted_at IS NULL
ORDER BY scheduled_at ASC
`

// Шедулер на каждом тике: пересдачи, которые пора стартовать
// (scheduled_at прошёл, статус всё ещё scheduled).
func (q *Queries) ListRetakesToStart(ctx context.Context) ([]Retake, error) {
	rows, err := q.db.Query(ctx, listRetakesToStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Retake
	for rows.Next() {
		var i Retake
		if err := rows.Scan(
			&i.ID,
			&i.DisciplineID,
			&i.Kind,
			&i.MinTeachers,
			&i.Building,
			&i.Room,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRetakeCompleted = `-- name: MarkRetakeCompleted :exec
UPDATE retakes
SET status       = 'completed',
    completed_at = NOW(),
    updated_at   = NOW()
WHERE id = $1
  AND status IN ('scheduled', 'in_progress')
  AND deleted_at IS NULL
`

// Шедулер переводит в completed по истечении scheduled_at + duration.
func (q *Queries) MarkRetakeCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRetakeCompleted, id)
	return err
}

const markRetakeInProgress = `-- name: MarkRetakeInProgress :exec
UPDATE retakes
SET status     = 'in_progress',
    updated_at = NOW()
WHERE id = $1
  AND status = 'scheduled'
  AND deleted_at IS NULL
`

// Шедулер переводит пересдачу в in_progress по достижении scheduled_at.
func (q *Queries) MarkRetakeInProgress(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRetakeInProgress, id)
	return err
}

const softDeleteRetake = `-- name: SoftDeleteRetake :exec
UPDATE retakes
SET deleted_at = NOW(),
    deleted_by = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type SoftDeleteRetakeParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteRetake(ctx context.Context, arg SoftDeleteRetakeParams) error {
	_, err := q.db.Exec(ctx, softDeleteRetake, arg.ID, arg.DeletedBy)
	return err
}

const updateRetakeSchedule = `-- name: UpdateRetakeSchedule :one
UPDATE retakes
SET building         = COALESCE($1,         building),
    room             = COALESCE($2,             room),
    scheduled_at     = COALESCE($3,     scheduled_at),
    duration_minutes = COALESCE($4, duration_minutes),
    notes            = COALESCE($5,            notes),
    updated_at       = NOW()
WHERE id = $6
  AND deleted_at IS NULL
RETURNING id, discipline_id, kind, min_teachers, building, room, scheduled_at, duration_minutes, status, completed_at, created_by, notes, created_at, updated_at, deleted_at, deleted_by
`

type UpdateRetakeScheduleParams struct {
	Building        *string            `json:"building"`
	Room            *string            `json:"room"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes *int32             `json:"duration_minutes"`
	Notes           *string            `json:"notes"`
	ID              pgtype.UUID        `json:"id"`
}

// Деканат меняет время/место/продолжительность пересдачи (например,
// по итогам одобренной change-request заявки от преподавателя).
func (q *Queries) UpdateRetakeSchedule(ctx context.Context, arg UpdateRetakeScheduleParams) (Retake, error) {
	row := q.db.QueryRow(ctx, updateRetakeSchedule,
		arg.Building,
		arg.Room,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.Notes,
		arg.ID,
	)
	var i Retake
	err := row.Scan(
		&i.ID,
		&i.DisciplineID,
		&i.Kind,
		&i.MinTeachers,
		&i.Building,
		&i.Room,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
