// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retake_participants.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO retake_participants (retake_id, user_id, kind, debt_id)
VALUES ($1, $2, $3, $4)
RETURNING id, retake_id, user_id, kind, debt_id, grade, graded_at, graded_by, created_at
`

type AddParticipantParams struct {
	RetakeID pgtype.UUID `json:"retake_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Kind     string      `json:"kind"`
	DebtID   pgtype.UUID `json:"debt_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (RetakeParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipant,
		arg.RetakeID,
		arg.UserID,
		arg.Kind,
		arg.DebtID,
	)
	var i RetakeParticipant
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.UserID,
		&i.Kind,
		&i.DebtID,
		&i.Grade,
		&i.GradedAt,
		&i.GradedBy,
		&i.CreatedAt,
	)
	return i, err
}

const countTeachersInRetake = `-- name: CountTeachersInRetake :one
SELECT COUNT(*)
FROM retake_participants
WHERE retake_id = $1
  AND kind IN ('teacher', 'commission_member')
`

// Проверка инварианта "commission требует ≥ 3 преподавателей" перед
// старшим переводом пересдачи в активный статус.
func (q *Queries) CountTeachersInRetake(ctx context.Context, retakeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeachersInRetake, retakeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, retake_id, user_id, kind, debt_id, grade, graded_at, graded_by, created_at
FROM retake_participants
WHERE id = $1
`

func (q *Queries) GetParticipant(ctx context.Context, id pgtype.UUID) (RetakeParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i RetakeParticipant
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.UserID,
		&i.Kind,
		&i.DebtID,
		&i.Grade,
		&i.GradedAt,
		&i.GradedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByRetakeAndUser = `-- name: GetParticipantByRetakeAndUser :one
SELECT id, retake_id, user_id, kind, debt_id, grade, graded_at, graded_by, created_at
FROM retake_participants
WHERE retake_id = $1
  AND user_id = $2
`

type GetParticipantByRetakeAndUserParams struct {
	RetakeID pgtype.UUID `json:"retake_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetParticipantByRetakeAndUser(ctx context.Context, arg GetParticipantByRetakeAndUserParams) (RetakeParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipantByRetakeAndUser, arg.RetakeID, arg.UserID)
	var i RetakeParticipant
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.UserID,
		&i.Kind,
		&i.DebtID,
		&i.Grade,
		&i.GradedAt,
		&i.GradedBy,
		&i.CreatedAt,
	)
	return i, err
}

const gradeStudentParticipant = `-- name: GradeStudentParticipant :one
UPDATE retake_participants
SET grade     = $2,
    graded_at = NOW(),
    graded_by = $3
WHERE id = $1
  AND kind = 'student'
  AND grade IS NULL
RETURNING id, retake_id, user_id, kind, debt_id, grade, graded_at, graded_by, created_at
`

type GradeStudentParticipantParams struct {
	ID       pgtype.UUID `json:"id"`
	Grade    *int32      `json:"grade"`
	GradedBy pgtype.UUID `json:"graded_by"`
}

// Выставление оценки участнику-студенту. Сервис вызывает это
// в той же транзакции, что и GradeDebt — чтобы retake_participants
// и debts остались согласованы.
func (q *Queries) GradeStudentParticipant(ctx context.Context, arg GradeStudentParticipantParams) (RetakeParticipant, error) {
	row := q.db.QueryRow(ctx, gradeStudentParticipant, arg.ID, arg.Grade, arg.GradedBy)
	var i RetakeParticipant
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.UserID,
		&i.Kind,
		&i.DebtID,
		&i.Grade,
		&i.GradedAt,
		&i.GradedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listParticipantsForRetake = `-- name: ListParticipantsForRetake :many
SELECT id, retake_id, user_id, kind, debt_id, grade, graded_at, graded_by, created_at
FROM retake_participants
WHERE retake_id = $1
ORDER BY kind ASC, created_at ASC
`

// Все участники пересдачи: студенты и преподаватели/комиссия вместе.
// На handler-уровне разделяются по полю kind.
func (q *Queries) ListParticipantsForRetake(ctx context.Context, retakeID pgtype.UUID) ([]RetakeParticipant, error) {
	rows, err := q.db.Query(ctx, listParticipantsForRetake, retakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetakeParticipant
	for rows.Next() {
		var i RetakeParticipant
		if err := rows.Scan(
			&i.ID,
			&i.RetakeID,
			&i.UserID,
			&i.Kind,
			&i.DebtID,
			&i.Grade,
			&i.GradedAt,
			&i.GradedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentParticipantsForRetake = `-- name: ListStudentParticipantsForRetake :many
SELECT rp.id, rp.retake_id, rp.user_id, rp.kind, rp.debt_id, rp.grade, rp.graded_at, rp.graded_by, rp.created_at, u.email, u.first_name, u.last_name, u.middle_name, u.group_name
FROM retake_participants rp
JOIN users u ON u.id = rp.user_id
WHERE rp.retake_id = $1
  AND rp.kind = 'student'
ORDER BY u.last_name ASC, u.first_name ASC
`

type ListStudentParticipantsForRetakeRow struct {
	ID         pgtype.UUID        `json:"id"`
	RetakeID   pgtype.UUID        `json:"retake_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Kind       string             `json:"kind"`
	DebtID     pgtype.UUID        `json:"debt_id"`
	Grade      *int32             `json:"grade"`
	GradedAt   pgtype.Timestamptz `json:"graded_at"`
	GradedBy   pgtype.UUID        `json:"graded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Email      string             `json:"email"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	MiddleName *string            `json:"middle_name"`
	GroupName  *string            `json:"group_name"`
}

// Только студенты пересдачи. Используется при выставлении оценок.
func (q *Queries) ListStudentParticipantsForRetake(ctx context.Context, retakeID pgtype.UUID) ([]ListStudentParticipantsForRetakeRow, error) {
	rows, err := q.db.Query(ctx, listStudentParticipantsForRetake, retakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentParticipantsForRetakeRow
	for rows.Next() {
		var i ListStudentParticipantsForRetakeRow
		if err := rows.Scan(
			&i.ID,
			&i.RetakeID,
			&i.UserID,
			&i.Kind,
			&i.DebtID,
			&i.Grade,
			&i.GradedAt,
			&i.GradedBy,
			&i.CreatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherParticipantsForRetake = `-- name: ListTeacherParticipantsForRetake :many
SELECT id, retake_id, user_id, kind, debt_id, grade, graded_at, graded_by, created_at
FROM retake_participants
WHERE retake_id = $1
  AND kind IN ('teacher', 'commission_member')
`

func (q *Queries) ListTeacherParticipantsForRetake(ctx context.Context, retakeID pgtype.UUID) ([]RetakeParticipant, error) {
	rows, err := q.db.Query(ctx, listTeacherParticipantsForRetake, retakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetakeParticipant
	for rows.Next() {
		var i RetakeParticipant
		if err := rows.Scan(
			&i.ID,
			&i.RetakeID,
			&i.UserID,
			&i.Kind,
			&i.DebtID,
			&i.Grade,
			&i.GradedAt,
			&i.GradedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipant = `-- name: RemoveParticipant :exec
DELETE FROM retake_participants
WHERE retake_id = $1
  AND user_id = $2
`

type RemoveParticipantParams struct {
	RetakeID pgtype.UUID `json:"retake_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Физическое удаление. Если пересдача уже стартовала или есть оценка —
// сервис должен отказать (проверка в бизнес-слое, не в БД).
func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.RetakeID, arg.UserID)
	return err
}

const upsertParticipantGradeDraft = `-- name: UpsertParticipantGradeDraft :one
UPDATE retake_participants
SET grade     = $2,
    graded_at = NOW(),
    graded_by = $3
WHERE id = $1
  AND kind = 'student'
RETURNING id, retake_id, user_id, kind, debt_id, grade, graded_at, graded_by, created_at
`

type UpsertParticipantGradeDraftParams struct {
	ID       pgtype.UUID `json:"id"`
	Grade    *int32      `json:"grade"`
	GradedBy pgtype.UUID `json:"graded_by"`
}

// Черновик оценки для двухэтапной ведомости. В отличие от
// GradeStudentParticipant здесь НЕТ "AND grade IS NULL" — черновик
// можно перезаписывать сколько угодно, пока ведомость open. Все три
// колонки (grade/graded_at/graded_by) ставятся всегда, иначе нарушится
// CHECK participants_grade_consistency. graded_by/at тут означают
// "кем/когда внесён черновик". Долг при этом НЕ закрывается — это
// делает CloseSheet.
func (q *Queries) UpsertParticipantGradeDraft(ctx context.Context, arg UpsertParticipantGradeDraftParams) (RetakeParticipant, error) {
	row := q.db.QueryRow(ctx, upsertParticipantGradeDraft, arg.ID, arg.Grade, arg.GradedBy)
	var i RetakeParticipant
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.UserID,
		&i.Kind,
		&i.DebtID,
		&i.Grade,
		&i.GradedAt,
		&i.GradedBy,
		&i.CreatedAt,
	)
	return i, err
}
