// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retake_requests.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRetakeRequest = `-- name: ApproveRetakeRequest :one
UPDATE retake_requests
SET status            = 'approved',
    reviewed_by       = $1::uuid,
    reviewed_at       = NOW(),
    decision_reason   = $2::text,
    created_retake_id = $3::uuid,
    updated_at        = NOW()
WHERE id = $4::uuid
  AND status = 'pending'
RETURNING id, requested_by, payload, status, reviewed_by, reviewed_at, decision_reason, created_retake_id, created_at, updated_at
`

type ApproveRetakeRequestParams struct {
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
	DecisionReason  *string     `json:"decision_reason"`
	CreatedRetakeID pgtype.UUID `json:"created_retake_id"`
	ID              pgtype.UUID `json:"id"`
}

// created_retake_id заполняется в сервисе уже после q.CreateRetake
// в той же транзакции — поэтому здесь это обязательный параметр.
func (q *Queries) ApproveRetakeRequest(ctx context.Context, arg ApproveRetakeRequestParams) (RetakeRequest, error) {
	row := q.db.QueryRow(ctx, approveRetakeRequest,
		arg.ReviewedBy,
		arg.DecisionReason,
		arg.CreatedRetakeID,
		arg.ID,
	)
	var i RetakeRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Payload,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedRetakeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRetakeRequest = `-- name: CreateRetakeRequest :one
INSERT INTO retake_requests (requested_by, payload)
VALUES ($1, $2)
RETURNING id, requested_by, payload, status, reviewed_by, reviewed_at, decision_reason, created_retake_id, created_at, updated_at
`

type CreateRetakeRequestParams struct {
	RequestedBy pgtype.UUID `json:"requested_by"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) CreateRetakeRequest(ctx context.Context, arg CreateRetakeRequestParams) (RetakeRequest, error) {
	row := q.db.QueryRow(ctx, createRetakeRequest, arg.RequestedBy, arg.Payload)
	var i RetakeRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Payload,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedRetakeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRetakeRequestByID = `-- name: GetRetakeRequestByID :one
SELECT id, requested_by, payload, status, reviewed_by, reviewed_at, decision_reason, created_retake_id, created_at, updated_at
FROM retake_requests
WHERE id = $1
`

func (q *Queries) GetRetakeRequestByID(ctx context.Context, id pgtype.UUID) (RetakeRequest, error) {
	row := q.db.QueryRow(ctx, getRetakeRequestByID, id)
	var i RetakeRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Payload,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedRetakeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingRetakeRequests = `-- name: ListPendingRetakeRequests :many
SELECT id, requested_by, payload, status, reviewed_by, reviewed_at, decision_reason, created_retake_id, created_at, updated_at
FROM retake_requests
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingRetakeRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Деканат: входящие заявки на рассмотрение.
func (q *Queries) ListPendingRetakeRequests(ctx context.Context, arg ListPendingRetakeRequestsParams) ([]RetakeRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRetakeRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetakeRequest
	for rows.Next() {
		var i RetakeRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Payload,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedRetakeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetakeRequestsForTeacher = `-- name: ListRetakeRequestsForTeacher :many
SELECT id, requested_by, payload, status, reviewed_by, reviewed_at, decision_reason, created_retake_id, created_at, updated_at
FROM retake_requests
WHERE requested_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRetakeRequestsForTeacherParams struct {
	RequestedBy pgtype.UUID `json:"requested_by"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// История заявок преподавателя (его собственные).
func (q *Queries) ListRetakeRequestsForTeacher(ctx context.Context, arg ListRetakeRequestsForTeacherParams) ([]RetakeRequest, error) {
	rows, err := q.db.Query(ctx, listRetakeRequestsForTeacher, arg.RequestedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetakeRequest
	for rows.Next() {
		var i RetakeRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Payload,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedRetakeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRetakeRequest = `-- name: RejectRetakeRequest :one
UPDATE retake_requests
SET status          = 'rejected',
    reviewed_by     = $1::uuid,
    reviewed_at     = NOW(),
    decision_reason = $2::text,
    updated_at      = NOW()
WHERE id = $3::uuid
  AND status = 'pending'
RETURNING id, requested_by, payload, status, reviewed_by, reviewed_at, decision_reason, created_retake_id, created_at, updated_at
`

type RejectRetakeRequestParams struct {
	ReviewedBy     pgtype.UUID `json:"reviewed_by"`
	DecisionReason string      `json:"decision_reason"`
	ID             pgtype.UUID `json:"id"`
}

// При rejected decision_reason обязателен — CHECK-constraint в таблице
// гарантирует это даже если сервис забудет передать.
func (q *Queries) RejectRetakeRequest(ctx context.Context, arg RejectRetakeRequestParams) (RetakeRequest, error) {
	row := q.db.QueryRow(ctx, rejectRetakeRequest, arg.ReviewedBy, arg.DecisionReason, arg.ID)
	var i RetakeRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Payload,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedRetakeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
