// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retake_change_requests.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRetakeChangeRequest = `-- name: ApproveRetakeChangeRequest :one
UPDATE retake_change_requests
SET status          = 'approved',
    reviewed_by     = $1::uuid,
    reviewed_at     = NOW(),
    decision_reason = $2::text,
    updated_at      = NOW()
WHERE id = $3::uuid
  AND status = 'pending'
RETURNING id, retake_id, requested_by, requested_changes, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
`

type ApproveRetakeChangeRequestParams struct {
	ReviewedBy     pgtype.UUID `json:"reviewed_by"`
	DecisionReason *string     `json:"decision_reason"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) ApproveRetakeChangeRequest(ctx context.Context, arg ApproveRetakeChangeRequestParams) (RetakeChangeRequest, error) {
	row := q.db.QueryRow(ctx, approveRetakeChangeRequest, arg.ReviewedBy, arg.DecisionReason, arg.ID)
	var i RetakeChangeRequest
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.RequestedBy,
		&i.RequestedChanges,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRetakeChangeRequest = `-- name: CreateRetakeChangeRequest :one
INSERT INTO retake_change_requests (retake_id, requested_by, requested_changes, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, retake_id, requested_by, requested_changes, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
`

type CreateRetakeChangeRequestParams struct {
	RetakeID         pgtype.UUID `json:"retake_id"`
	RequestedBy      pgtype.UUID `json:"requested_by"`
	RequestedChanges []byte      `json:"requested_changes"`
	Reason           *string     `json:"reason"`
}

func (q *Queries) CreateRetakeChangeRequest(ctx context.Context, arg CreateRetakeChangeRequestParams) (RetakeChangeRequest, error) {
	row := q.db.QueryRow(ctx, createRetakeChangeRequest,
		arg.RetakeID,
		arg.RequestedBy,
		arg.RequestedChanges,
		arg.Reason,
	)
	var i RetakeChangeRequest
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.RequestedBy,
		&i.RequestedChanges,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRetakeChangeRequestByID = `-- name: GetRetakeChangeRequestByID :one
SELECT id, retake_id, requested_by, requested_changes, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM retake_change_requests
WHERE id = $1
`

func (q *Queries) GetRetakeChangeRequestByID(ctx context.Context, id pgtype.UUID) (RetakeChangeRequest, error) {
	row := q.db.QueryRow(ctx, getRetakeChangeRequestByID, id)
	var i RetakeChangeRequest
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.RequestedBy,
		&i.RequestedChanges,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingRetakeChangeRequests = `-- name: ListPendingRetakeChangeRequests :many
SELECT id, retake_id, requested_by, requested_changes, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM retake_change_requests
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingRetakeChangeRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Деканат: входящие заявки на рассмотрение.
func (q *Queries) ListPendingRetakeChangeRequests(ctx context.Context, arg ListPendingRetakeChangeRequestsParams) ([]RetakeChangeRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRetakeChangeRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetakeChangeRequest
	for rows.Next() {
		var i RetakeChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.RetakeID,
			&i.RequestedBy,
			&i.RequestedChanges,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetakeChangeRequestsForRetake = `-- name: ListRetakeChangeRequestsForRetake :many
SELECT id, retake_id, requested_by, requested_changes, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM retake_change_requests
WHERE retake_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRetakeChangeRequestsForRetake(ctx context.Context, retakeID pgtype.UUID) ([]RetakeChangeRequest, error) {
	rows, err := q.db.Query(ctx, listRetakeChangeRequestsForRetake, retakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetakeChangeRequest
	for rows.Next() {
		var i RetakeChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.RetakeID,
			&i.RequestedBy,
			&i.RequestedChanges,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetakeChangeRequestsForTeacher = `-- name: ListRetakeChangeRequestsForTeacher :many
SELECT id, retake_id, requested_by, requested_changes, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM retake_change_requests
WHERE requested_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRetakeChangeRequestsForTeacherParams struct {
	RequestedBy pgtype.UUID `json:"requested_by"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// История заявок преподавателя.
func (q *Queries) ListRetakeChangeRequestsForTeacher(ctx context.Context, arg ListRetakeChangeRequestsForTeacherParams) ([]RetakeChangeRequest, error) {
	rows, err := q.db.Query(ctx, listRetakeChangeRequestsForTeacher, arg.RequestedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetakeChangeRequest
	for rows.Next() {
		var i RetakeChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.RetakeID,
			&i.RequestedBy,
			&i.RequestedChanges,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRetakeChangeRequest = `-- name: RejectRetakeChangeRequest :one
UPDATE retake_change_requests
SET status          = 'rejected',
    reviewed_by     = $1::uuid,
    reviewed_at     = NOW(),
    decision_reason = $2::text,
    updated_at      = NOW()
WHERE id = $3::uuid
  AND status = 'pending'
RETURNING id, retake_id, requested_by, requested_changes, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
`

type RejectRetakeChangeRequestParams struct {
	ReviewedBy     pgtype.UUID `json:"reviewed_by"`
	DecisionReason string      `json:"decision_reason"`
	ID             pgtype.UUID `json:"id"`
}

// При rejected decision_reason обязателен — CHECK-constraint в таблице
// гарантирует это даже если сервис забудет передать.
func (q *Queries) RejectRetakeChangeRequest(ctx context.Context, arg RejectRetakeChangeRequestParams) (RetakeChangeRequest, error) {
	row := q.db.QueryRow(ctx, rejectRetakeChangeRequest, arg.ReviewedBy, arg.DecisionReason, arg.ID)
	var i RetakeChangeRequest
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.RequestedBy,
		&i.RequestedChanges,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
