// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_user.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachRoleToUser = `-- name: AttachRoleToUser :one
INSERT INTO role_user (user_id, role_id, created_by)
VALUES ($1, $2, $3)
RETURNING id, user_id, role_id, created_at, created_by, deleted_at, deleted_by
`

type AttachRoleToUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	RoleID    pgtype.UUID `json:"role_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

// Идемпотентно: при повторной выдаче той же роли SoftDelete ничего не
// меняет, INSERT даст конфликт по уникальному индексу. Идемпотентность
// обеспечивается на уровне сервиса (сначала проверка существования).
func (q *Queries) AttachRoleToUser(ctx context.Context, arg AttachRoleToUserParams) (RoleUser, error) {
	row := q.db.QueryRow(ctx, attachRoleToUser, arg.UserID, arg.RoleID, arg.CreatedBy)
	var i RoleUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const detachRoleFromUser = `-- name: DetachRoleFromUser :exec
UPDATE role_user
SET deleted_at = NOW(),
    deleted_by = $3
WHERE user_id = $1
  AND role_id = $2
  AND deleted_at IS NULL
`

type DetachRoleFromUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	RoleID    pgtype.UUID `json:"role_id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DetachRoleFromUser(ctx context.Context, arg DetachRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, detachRoleFromUser, arg.UserID, arg.RoleID, arg.DeletedBy)
	return err
}

const hasRole = `-- name: HasRole :one
SELECT EXISTS (
    SELECT 1
    FROM role_user ru
    JOIN roles r ON r.id = ru.role_id
    WHERE ru.user_id = $1
      AND LOWER(r.slug) = LOWER($2)
      AND ru.deleted_at IS NULL
      AND r.deleted_at IS NULL
) AS has_role
`

type HasRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Lower  string      `json:"lower"`
}

// Проверка наличия конкретной роли у пользователя.
func (q *Queries) HasRole(ctx context.Context, arg HasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRole, arg.UserID, arg.Lower)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const listPermissionsForUser = `-- name: ListPermissionsForUser :many
SELECT DISTINCT p.slug
FROM role_user ru
JOIN permission_role pr ON pr.role_id = ru.role_id
JOIN permissions p ON p.id = pr.permission_id
JOIN roles r ON r.id = ru.role_id
WHERE ru.user_id = $1
  AND ru.deleted_at IS NULL
  AND pr.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND r.deleted_at IS NULL
ORDER BY p.slug ASC
`

// Возвращает все активные slug'и разрешений, доступных пользователю
// через его роли. Дубли убираются DISTINCT, потому что один permission
// может быть прикреплён к нескольким ролям пользователя.
func (q *Queries) ListPermissionsForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT r.id, r.name, r.slug, r.description, r.level, r.is_system, r.created_at, r.created_by, r.updated_at, r.deleted_at, r.deleted_by
FROM roles r
JOIN role_user ru ON ru.role_id = r.id
WHERE ru.user_id = $1
  AND ru.deleted_at IS NULL
  AND r.deleted_at IS NULL
ORDER BY r.level DESC
`

func (q *Queries) ListRolesForUser(ctx context.Context, userID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Level,
			&i.IsSystem,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInRole = `-- name: ListUsersInRole :many
SELECT u.id, u.email, u.password_hash, u.first_name, u.last_name, u.middle_name, u.birthday, u.group_name, u.created_at, u.updated_at, u.external_id
FROM users u
JOIN role_user ru ON ru.user_id = u.id
WHERE ru.role_id = $1
  AND ru.deleted_at IS NULL
ORDER BY u.last_name ASC, u.first_name ASC
`

func (q *Queries) ListUsersInRole(ctx context.Context, roleID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersInRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Birthday,
			&i.GroupName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userHasPermission = `-- name: UserHasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM role_user ru
    JOIN permission_role pr ON pr.role_id = ru.role_id
    JOIN permissions p ON p.id = pr.permission_id
    JOIN roles r ON r.id = ru.role_id
    WHERE ru.user_id = $1
      AND LOWER(p.slug) = LOWER($2)
      AND ru.deleted_at IS NULL
      AND pr.deleted_at IS NULL
      AND p.deleted_at IS NULL
      AND r.deleted_at IS NULL
) AS has_permission
`

type UserHasPermissionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Lower  string      `json:"lower"`
}

// Точечная проверка на конкретный permission по slug. Используется в
// RBAC-middleware на каждом защищённом запросе.
func (q *Queries) UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasPermission, arg.UserID, arg.Lower)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
