// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, slug, description, level, is_system, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, description, level, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
`

type CreateRoleParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description *string     `json:"description"`
	Level       int32       `json:"level"`
	IsSystem    bool        `json:"is_system"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Level,
		arg.IsSystem,
		arg.CreatedBy,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, slug, description, level, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
FROM roles
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, name, slug, description, level, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
FROM roles
WHERE LOWER(slug) = LOWER($1)
  AND deleted_at IS NULL
`

func (q *Queries) GetRoleBySlug(ctx context.Context, lower string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, lower)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, slug, description, level, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
FROM roles
WHERE deleted_at IS NULL
ORDER BY level DESC, name ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Level,
			&i.IsSystem,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesIncludingDeleted = `-- name: ListRolesIncludingDeleted :many
SELECT id, name, slug, description, level, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
FROM roles
ORDER BY level DESC, name ASC
`

// Для админ-интерфейса просмотра истории.
func (q *Queries) ListRolesIncludingDeleted(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesIncludingDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Level,
			&i.IsSystem,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreRole = `-- name: RestoreRole :exec
UPDATE roles
SET deleted_at = NULL,
    deleted_by = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreRole, id)
	return err
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE roles
SET deleted_at = NOW(),
    deleted_by = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SoftDeleteRoleParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

// Системные роли (is_system=TRUE) защищаются от удаления на уровне
// сервиса — здесь жёсткой проверки нет, чтобы запрос оставался
// переиспользуемым.
func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) error {
	_, err := q.db.Exec(ctx, softDeleteRole, arg.ID, arg.DeletedBy)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name        = COALESCE($1,        name),
    description = COALESCE($2, description),
    level       = COALESCE($3,       level),
    updated_at  = NOW()
WHERE id = $4
  AND deleted_at IS NULL
RETURNING id, name, slug, description, level, is_system, created_at, created_by, updated_at, deleted_at, deleted_by
`

type UpdateRoleParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Level       *int32      `json:"level"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Description,
		arg.Level,
		arg.ID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Level,
		&i.IsSystem,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
