// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statement_sheets.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeStatementSheet = `-- name: CloseStatementSheet :one
UPDATE statement_sheets
SET status     = 'closed',
    closed_at  = NOW(),
    closed_by  = $2,
    updated_at = NOW()
WHERE retake_id = $1
  AND status = 'open'
RETURNING id, retake_id, status, closed_at, closed_by, reopened_at, reopened_by, created_at, updated_at
`

type CloseStatementSheetParams struct {
	RetakeID pgtype.UUID `json:"retake_id"`
	ClosedBy pgtype.UUID `json:"closed_by"`
}

// open → closed. WHERE status='open' отсекает повторное закрытие/гонку
// (вернёт ErrNoRows → сервис трактует как ErrSheetClosed).
func (q *Queries) CloseStatementSheet(ctx context.Context, arg CloseStatementSheetParams) (StatementSheet, error) {
	row := q.db.QueryRow(ctx, closeStatementSheet, arg.RetakeID, arg.ClosedBy)
	var i StatementSheet
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.Status,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.ReopenedAt,
		&i.ReopenedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStatementSheet = `-- name: CreateStatementSheet :one
INSERT INTO statement_sheets (retake_id)
VALUES ($1)
ON CONFLICT (retake_id) DO NOTHING
RETURNING id, retake_id, status, closed_at, closed_by, reopened_at, reopened_by, created_at, updated_at
`

// Идемпотентный lazy-create ведомости. При гонке первого обращения
// (два запроса одновременно) второй INSERT ничего не делает из-за
// UNIQUE на retake_id — сервис затем читает строку через
// GetStatementSheetByRetake. RETURNING вернёт строку только когда
// вставка реально произошла; при конфликте — пусто (ErrNoRows).
func (q *Queries) CreateStatementSheet(ctx context.Context, retakeID pgtype.UUID) (StatementSheet, error) {
	row := q.db.QueryRow(ctx, createStatementSheet, retakeID)
	var i StatementSheet
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.Status,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.ReopenedAt,
		&i.ReopenedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatementSheetByRetake = `-- name: GetStatementSheetByRetake :one
SELECT id, retake_id, status, closed_at, closed_by, reopened_at, reopened_by, created_at, updated_at
FROM statement_sheets
WHERE retake_id = $1
`

func (q *Queries) GetStatementSheetByRetake(ctx context.Context, retakeID pgtype.UUID) (StatementSheet, error) {
	row := q.db.QueryRow(ctx, getStatementSheetByRetake, retakeID)
	var i StatementSheet
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.Status,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.ReopenedAt,
		&i.ReopenedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reopenStatementSheet = `-- name: ReopenStatementSheet :one
UPDATE statement_sheets
SET status      = 'open',
    closed_at   = NULL,
    closed_by   = NULL,
    reopened_at = NOW(),
    reopened_by = $2,
    updated_at  = NOW()
WHERE retake_id = $1
  AND status = 'closed'
RETURNING id, retake_id, status, closed_at, closed_by, reopened_at, reopened_by, created_at, updated_at
`

type ReopenStatementSheetParams struct {
	RetakeID   pgtype.UUID `json:"retake_id"`
	ReopenedBy pgtype.UUID `json:"reopened_by"`
}

// closed → open (декан). Сбрасываем closed_*, фиксируем reopened_*.
// WHERE status='closed' отсекает повторное открытие/гонку.
func (q *Queries) ReopenStatementSheet(ctx context.Context, arg ReopenStatementSheetParams) (StatementSheet, error) {
	row := q.db.QueryRow(ctx, reopenStatementSheet, arg.RetakeID, arg.ReopenedBy)
	var i StatementSheet
	err := row.Scan(
		&i.ID,
		&i.RetakeID,
		&i.Status,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.ReopenedAt,
		&i.ReopenedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
