// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_disciplines.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachStudentToDiscipline = `-- name: AttachStudentToDiscipline :one
INSERT INTO student_disciplines (student_id, discipline_id, academic_year, semester, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, student_id, discipline_id, academic_year, semester, source, created_at, deleted_at
`

type AttachStudentToDisciplineParams struct {
	StudentID    pgtype.UUID `json:"student_id"`
	DisciplineID pgtype.UUID `json:"discipline_id"`
	AcademicYear *string     `json:"academic_year"`
	Semester     *int32      `json:"semester"`
	Source       string      `json:"source"`
}

func (q *Queries) AttachStudentToDiscipline(ctx context.Context, arg AttachStudentToDisciplineParams) (StudentDiscipline, error) {
	row := q.db.QueryRow(ctx, attachStudentToDiscipline,
		arg.StudentID,
		arg.DisciplineID,
		arg.AcademicYear,
		arg.Semester,
		arg.Source,
	)
	var i StudentDiscipline
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.DisciplineID,
		&i.AcademicYear,
		&i.Semester,
		&i.Source,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const detachStudentFromDiscipline = `-- name: DetachStudentFromDiscipline :exec
UPDATE student_disciplines
SET deleted_at = NOW()
WHERE student_id = $1
  AND discipline_id = $2
  AND deleted_at IS NULL
`

type DetachStudentFromDisciplineParams struct {
	StudentID    pgtype.UUID `json:"student_id"`
	DisciplineID pgtype.UUID `json:"discipline_id"`
}

func (q *Queries) DetachStudentFromDiscipline(ctx context.Context, arg DetachStudentFromDisciplineParams) error {
	_, err := q.db.Exec(ctx, detachStudentFromDiscipline, arg.StudentID, arg.DisciplineID)
	return err
}

const isStudentEnrolled = `-- name: IsStudentEnrolled :one
SELECT EXISTS (
    SELECT 1
    FROM student_disciplines
    WHERE student_id = $1
      AND discipline_id = $2
      AND deleted_at IS NULL
) AS enrolled
`

type IsStudentEnrolledParams struct {
	StudentID    pgtype.UUID `json:"student_id"`
	DisciplineID pgtype.UUID `json:"discipline_id"`
}

// Быстрая проверка для сервиса debts: можно ли поставить долг
// этому студенту по этой дисциплине.
func (q *Queries) IsStudentEnrolled(ctx context.Context, arg IsStudentEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isStudentEnrolled, arg.StudentID, arg.DisciplineID)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}

const listDisciplinesForStudent = `-- name: ListDisciplinesForStudent :many
SELECT d.id, d.name, d.code, d.description, d.external_id, d.source, d.created_at, d.created_by, d.updated_at, d.deleted_at, d.deleted_by
FROM disciplines d
JOIN student_disciplines sd ON sd.discipline_id = d.id
WHERE sd.student_id = $1
  AND sd.deleted_at IS NULL
  AND d.deleted_at IS NULL
ORDER BY d.name ASC
`

// Какие дисциплины изучает студент. Используется в личном кабинете
// и при создании долга (валидируем, что студент учится на дисциплине).
func (q *Queries) ListDisciplinesForStudent(ctx context.Context, studentID pgtype.UUID) ([]Discipline, error) {
	rows, err := q.db.Query(ctx, listDisciplinesForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Discipline
	for rows.Next() {
		var i Discipline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.ExternalID,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsInDiscipline = `-- name: ListStudentsInDiscipline :many
SELECT u.id, u.email, u.password_hash, u.first_name, u.last_name, u.middle_name, u.birthday, u.group_name, u.created_at, u.updated_at, u.external_id
FROM users u
JOIN student_disciplines sd ON sd.student_id = u.id
WHERE sd.discipline_id = $1
  AND sd.deleted_at IS NULL
ORDER BY u.last_name ASC, u.first_name ASC
`

// Кто на дисциплине учится. Деканат использует для сводных отчётов.
func (q *Queries) ListStudentsInDiscipline(ctx context.Context, disciplineID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listStudentsInDiscipline, disciplineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Birthday,
			&i.GroupName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
