// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teacher_disciplines.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTeacherToDiscipline = `-- name: AttachTeacherToDiscipline :one
INSERT INTO teacher_disciplines (teacher_id, discipline_id, created_by)
VALUES ($1, $2, $3)
RETURNING id, teacher_id, discipline_id, created_at, created_by, deleted_at, deleted_by
`

type AttachTeacherToDisciplineParams struct {
	TeacherID    pgtype.UUID `json:"teacher_id"`
	DisciplineID pgtype.UUID `json:"discipline_id"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) AttachTeacherToDiscipline(ctx context.Context, arg AttachTeacherToDisciplineParams) (TeacherDiscipline, error) {
	row := q.db.QueryRow(ctx, attachTeacherToDiscipline, arg.TeacherID, arg.DisciplineID, arg.CreatedBy)
	var i TeacherDiscipline
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.DisciplineID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const detachTeacherFromDiscipline = `-- name: DetachTeacherFromDiscipline :exec
UPDATE teacher_disciplines
SET deleted_at = NOW(),
    deleted_by = $3
WHERE teacher_id = $1
  AND discipline_id = $2
  AND deleted_at IS NULL
`

type DetachTeacherFromDisciplineParams struct {
	TeacherID    pgtype.UUID `json:"teacher_id"`
	DisciplineID pgtype.UUID `json:"discipline_id"`
	DeletedBy    pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DetachTeacherFromDiscipline(ctx context.Context, arg DetachTeacherFromDisciplineParams) error {
	_, err := q.db.Exec(ctx, detachTeacherFromDiscipline, arg.TeacherID, arg.DisciplineID, arg.DeletedBy)
	return err
}

const isTeacherOfDiscipline = `-- name: IsTeacherOfDiscipline :one
SELECT EXISTS (
    SELECT 1
    FROM teacher_disciplines
    WHERE teacher_id = $1
      AND discipline_id = $2
      AND deleted_at IS NULL
) AS is_teacher
`

type IsTeacherOfDisciplineParams struct {
	TeacherID    pgtype.UUID `json:"teacher_id"`
	DisciplineID pgtype.UUID `json:"discipline_id"`
}

// RBAC-фильтр: преподаватель имеет debts.view.by_discipline только
// для своих дисциплин. Сервис вызывает это перед выдачей списка долгов.
func (q *Queries) IsTeacherOfDiscipline(ctx context.Context, arg IsTeacherOfDisciplineParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherOfDiscipline, arg.TeacherID, arg.DisciplineID)
	var is_teacher bool
	err := row.Scan(&is_teacher)
	return is_teacher, err
}

const listDisciplinesForTeacher = `-- name: ListDisciplinesForTeacher :many
SELECT d.id, d.name, d.code, d.description, d.external_id, d.source, d.created_at, d.created_by, d.updated_at, d.deleted_at, d.deleted_by
FROM disciplines d
JOIN teacher_disciplines td ON td.discipline_id = d.id
WHERE td.teacher_id = $1
  AND td.deleted_at IS NULL
  AND d.deleted_at IS NULL
ORDER BY d.name ASC
`

// Дисциплины конкретного преподавателя. Используется в его кабинете
// и для построения фильтра debts.view.by_discipline.
func (q *Queries) ListDisciplinesForTeacher(ctx context.Context, teacherID pgtype.UUID) ([]Discipline, error) {
	rows, err := q.db.Query(ctx, listDisciplinesForTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Discipline
	for rows.Next() {
		var i Discipline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.ExternalID,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachersForDiscipline = `-- name: ListTeachersForDiscipline :many
SELECT u.id, u.email, u.password_hash, u.first_name, u.last_name, u.middle_name, u.birthday, u.group_name, u.created_at, u.updated_at
FROM users u
JOIN teacher_disciplines td ON td.teacher_id = u.id
WHERE td.discipline_id = $1
  AND td.deleted_at IS NULL
ORDER BY u.last_name ASC, u.first_name ASC
`

func (q *Queries) ListTeachersForDiscipline(ctx context.Context, disciplineID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listTeachersForDiscipline, disciplineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Birthday,
			&i.GroupName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
