// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teacher_role_requests.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveTeacherRoleRequest = `-- name: ApproveTeacherRoleRequest :one
UPDATE teacher_role_requests
SET status          = 'approved',
    reviewed_by     = $1::uuid,
    reviewed_at     = NOW(),
    decision_reason = $2::text,
    updated_at      = NOW()
WHERE id = $3::uuid
  AND status = 'pending'
RETURNING id, requested_by, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
`

type ApproveTeacherRoleRequestParams struct {
	ReviewedBy     pgtype.UUID `json:"reviewed_by"`
	DecisionReason *string     `json:"decision_reason"`
	ID             pgtype.UUID `json:"id"`
}

// Сервис вызывает в одной транзакции с AttachRoleToUser(teacher).
func (q *Queries) ApproveTeacherRoleRequest(ctx context.Context, arg ApproveTeacherRoleRequestParams) (TeacherRoleRequest, error) {
	row := q.db.QueryRow(ctx, approveTeacherRoleRequest, arg.ReviewedBy, arg.DecisionReason, arg.ID)
	var i TeacherRoleRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeacherRoleRequest = `-- name: CreateTeacherRoleRequest :one
INSERT INTO teacher_role_requests (requested_by, reason)
VALUES ($1, $2)
RETURNING id, requested_by, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
`

type CreateTeacherRoleRequestParams struct {
	RequestedBy pgtype.UUID `json:"requested_by"`
	Reason      *string     `json:"reason"`
}

func (q *Queries) CreateTeacherRoleRequest(ctx context.Context, arg CreateTeacherRoleRequestParams) (TeacherRoleRequest, error) {
	row := q.db.QueryRow(ctx, createTeacherRoleRequest, arg.RequestedBy, arg.Reason)
	var i TeacherRoleRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingTeacherRoleRequestForUser = `-- name: GetPendingTeacherRoleRequestForUser :one
SELECT id, requested_by, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM teacher_role_requests
WHERE requested_by = $1
  AND status = 'pending'
`

// Перед созданием новой заявки сервис проверяет наличие текущей
// pending — иначе UNIQUE-индекс idx_teacher_role_requests_unique_pending
// даст ошибку БД.
func (q *Queries) GetPendingTeacherRoleRequestForUser(ctx context.Context, requestedBy pgtype.UUID) (TeacherRoleRequest, error) {
	row := q.db.QueryRow(ctx, getPendingTeacherRoleRequestForUser, requestedBy)
	var i TeacherRoleRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherRoleRequestByID = `-- name: GetTeacherRoleRequestByID :one
SELECT id, requested_by, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM teacher_role_requests
WHERE id = $1
`

func (q *Queries) GetTeacherRoleRequestByID(ctx context.Context, id pgtype.UUID) (TeacherRoleRequest, error) {
	row := q.db.QueryRow(ctx, getTeacherRoleRequestByID, id)
	var i TeacherRoleRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTeacherRoleRequests = `-- name: ListPendingTeacherRoleRequests :many
SELECT id, requested_by, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM teacher_role_requests
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingTeacherRoleRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Деканат: входящие на рассмотрение.
func (q *Queries) ListPendingTeacherRoleRequests(ctx context.Context, arg ListPendingTeacherRoleRequestsParams) ([]TeacherRoleRequest, error) {
	rows, err := q.db.Query(ctx, listPendingTeacherRoleRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeacherRoleRequest
	for rows.Next() {
		var i TeacherRoleRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherRoleRequestsForUser = `-- name: ListTeacherRoleRequestsForUser :many
SELECT id, requested_by, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
FROM teacher_role_requests
WHERE requested_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTeacherRoleRequestsForUserParams struct {
	RequestedBy pgtype.UUID `json:"requested_by"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListTeacherRoleRequestsForUser(ctx context.Context, arg ListTeacherRoleRequestsForUserParams) ([]TeacherRoleRequest, error) {
	rows, err := q.db.Query(ctx, listTeacherRoleRequestsForUser, arg.RequestedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeacherRoleRequest
	for rows.Next() {
		var i TeacherRoleRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectTeacherRoleRequest = `-- name: RejectTeacherRoleRequest :one
UPDATE teacher_role_requests
SET status          = 'rejected',
    reviewed_by     = $1::uuid,
    reviewed_at     = NOW(),
    decision_reason = $2::text,
    updated_at      = NOW()
WHERE id = $3::uuid
  AND status = 'pending'
RETURNING id, requested_by, reason, status, reviewed_by, reviewed_at, decision_reason, created_at, updated_at
`

type RejectTeacherRoleRequestParams struct {
	ReviewedBy     pgtype.UUID `json:"reviewed_by"`
	DecisionReason string      `json:"decision_reason"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) RejectTeacherRoleRequest(ctx context.Context, arg RejectTeacherRoleRequestParams) (TeacherRoleRequest, error) {
	row := q.db.QueryRow(ctx, rejectTeacherRoleRequest, arg.ReviewedBy, arg.DecisionReason, arg.ID)
	var i TeacherRoleRequest
	err := row.Scan(
		&i.ID,
		&i.RequestedBy,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
