// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(DISTINCT u.id)
FROM users u
LEFT JOIN role_user ru ON ru.user_id = u.id AND ru.deleted_at IS NULL
LEFT JOIN roles r      ON r.id = ru.role_id  AND r.deleted_at  IS NULL
WHERE
    ($1::text IS NULL OR r.slug = $1::text)
AND ($2::text    IS NULL OR (
        u.email      ILIKE '%' || $2::text || '%'
     OR u.first_name ILIKE '%' || $2::text || '%'
     OR u.last_name  ILIKE '%' || $2::text || '%'
    ))
AND ($3::text IS NULL OR u.group_name = $3::text)
`

type CountUsersParams struct {
	RoleSlug  *string `json:"role_slug"`
	Search    *string `json:"search"`
	GroupName *string `json:"group_name"`
}

// Считает с теми же фильтрами что и ListUsers — для total в пагинации.
func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.RoleSlug, arg.Search, arg.GroupName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, first_name, last_name, middle_name, birthday, group_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, password_hash, first_name, last_name, middle_name, birthday, group_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	MiddleName   *string     `json:"middle_name"`
	Birthday     pgtype.Date `json:"birthday"`
	GroupName    *string     `json:"group_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Birthday,
		arg.GroupName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Birthday,
		&i.GroupName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, middle_name, birthday, group_name, created_at, updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
`

// Поиск пользователя по email для логина. Сравнение регистронезависимое
// (соответствует UNIQUE-индексу idx_users_email_lower).
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Birthday,
		&i.GroupName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, middle_name, birthday, group_name, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Birthday,
		&i.GroupName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, email, password_hash, first_name, last_name, middle_name, birthday, group_name, created_at, updated_at
FROM users
WHERE id = ANY($1::uuid[])
`

// Батч-выборка пользователей по списку ID. Используется в report.Service
// вместо N одиночных GetUserByID.
func (q *Queries) ListUsersByIDs(ctx context.Context, ids []pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Birthday,
			&i.GroupName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT DISTINCT u.id, u.email, u.password_hash, u.first_name, u.last_name, u.middle_name, u.birthday, u.group_name, u.created_at, u.updated_at
FROM users u
LEFT JOIN role_user ru ON ru.user_id = u.id AND ru.deleted_at IS NULL
LEFT JOIN roles r      ON r.id = ru.role_id  AND r.deleted_at  IS NULL
WHERE
    ($1::text IS NULL OR r.slug = $1::text)
AND ($2::text    IS NULL OR (
        u.email      ILIKE '%' || $2::text || '%'
     OR u.first_name ILIKE '%' || $2::text || '%'
     OR u.last_name  ILIKE '%' || $2::text || '%'
    ))
AND ($3::text IS NULL OR u.group_name = $3::text)
ORDER BY u.last_name ASC, u.first_name ASC, u.id ASC
LIMIT $5::int OFFSET $4::int
`

type ListUsersParams struct {
	RoleSlug  *string `json:"role_slug"`
	Search    *string `json:"search"`
	GroupName *string `json:"group_name"`
	OffsetN   int32   `json:"offset_n"`
	LimitN    int32   `json:"limit_n"`
}

// Список пользователей с опциональными фильтрами. Используется для
// админ-панели и для UI деканата (выбор преподавателя при создании
// пересдачи, выбор студента для привязки к дисциплине).
//
// Все фильтры опциональны:
//
//	role_slug   — если задан, отдаём только пользователей с этой ролью
//	              (JOIN с role_user + roles WHERE r.slug = ...)
//	search      — подстрока (ILIKE) по email, first_name, last_name
//	group_name  — точный матч (для отбора студентов по группе)
//
// Сортировка по фамилии — так удобнее листать. limit/offset для пагинации.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.RoleSlug,
		arg.Search,
		arg.GroupName,
		arg.OffsetN,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Birthday,
			&i.GroupName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name  = COALESCE($1,  first_name),
    last_name   = COALESCE($2,   last_name),
    middle_name = COALESCE($3, middle_name),
    birthday    = COALESCE($4,    birthday),
    group_name  = COALESCE($5,  group_name),
    updated_at  = NOW()
WHERE id = $6
RETURNING id, email, password_hash, first_name, last_name, middle_name, birthday, group_name, created_at, updated_at
`

type UpdateUserProfileParams struct {
	FirstName  *string     `json:"first_name"`
	LastName   *string     `json:"last_name"`
	MiddleName *string     `json:"middle_name"`
	Birthday   pgtype.Date `json:"birthday"`
	GroupName  *string     `json:"group_name"`
	ID         pgtype.UUID `json:"id"`
}

// Точечное обновление профиля. NULL-значения в параметрах оставляют поле
// без изменений (COALESCE), что упрощает PATCH-семантику на handler-слое.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Birthday,
		arg.GroupName,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Birthday,
		&i.GroupName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
